# Generated by Django 3.1.5 on 2021-01-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('gameid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('gamename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='invitee',
            fields=[
                ('inviteeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('inviteename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kittyparty',
            fields=[
                ('partyid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('partyname', models.CharField(max_length=50)),
                ('partydate', models.DateField()),
                ('partyvenue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='inviteepartybridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kittypartyapp.invitee')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kittypartyapp.kittyparty')),
            ],
        ),
        migrations.CreateModel(
            name='gamepartybridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kittypartyapp.game')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kittypartyapp.kittyparty')),
            ],
        ),
    ]
