# Generated by Django 3.1.5 on 2021-02-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0002_auto_20210203_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
    ]
