# Generated by Django 3.1.5 on 2021-03-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menuid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('menuname', models.CharField(max_length=50)),
                ('categoryid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='kittypartyapp.category')),
            ],
        ),
    ]
