# Generated by Django 3.1.5 on 2021-03-10 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='menupartybridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kittypartyapp.menu')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kittypartyapp.kittyparty')),
            ],
        ),
    ]
