# Generated by Django 3.1.5 on 2021-03-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0005_menupartybridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=30, verbose_name='Course Name')),
                ('coursefee', models.PositiveIntegerField()),
                ('courselevel', models.CharField(max_length=30, verbose_name='Level')),
                ('courseyear', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=50, verbose_name='Name')),
                ('studentadharno', models.CharField(max_length=17, verbose_name='Adhar No')),
                ('studentdob', models.DateField(verbose_name='DOB')),
                ('studentgender', models.BooleanField(verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='studentcourse',
            fields=[
                ('scid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('startdate', models.DateField(verbose_name='start date')),
                ('enddate', models.DateField(verbose_name='end date')),
                ('percentageofcompletion', models.PositiveSmallIntegerField(verbose_name='per of completion')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='kittypartyapp.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='kittypartyapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='studentcourse',
            field=models.ManyToManyField(related_name='student', through='kittypartyapp.studentcourse', to='kittypartyapp.course'),
        ),
    ]
