# Generated by Django 3.1.5 on 2021-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0006_auto_20210328_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentgender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
    ]
