# Generated by Django 3.1.5 on 2022-02-20 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kittypartyapp', '0007_auto_20210329_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=40, unique=True)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('max_student', models.IntegerField()),
                ('class_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDivya',
            fields=[
                ('student_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=40)),
                ('student_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('student_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, verbose_name='Gender')),
                ('guardian_name', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=20, unique=True, verbose_name='Contact Number')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Student_Bridge',
            fields=[
                ('cs_bridgeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student_bridge', to='kittypartyapp.classes')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student_bridge', to='kittypartyapp.studentdivya')),
            ],
        ),
    ]
